#ifndef RISCV_CUSTOMCSR_ENCODING_H
#define RISCV_CUSTOMCSR_ENCODING_H

#define MUARTSTAT_RXEMPTY 0x00000001
#define MUARTSTAT_RXFULL  0x00000002
#define MUARTSTAT_TXEMPTY 0x00000004
#define MUARTSTAT_TXFULL  0x00000008

#define MBFSSTAT_FOUND 0x00000001
#define MBFSSTAT_DONE  0x00000002

#define CSR_MUARTSTAT 0xfc0
#define CSR_MUARTRX 0xfc1
#define CSR_MUARTTX 0x7c0
#define CSR_MBFSSTAT 0x7d0
#define CSR_MBFSROOT 0x7d1
#define CSR_MBFSTARG 0x7d2
#define CSR_MBFSQBASE 0x7d3
#define CSR_MBFSQSIZE 0x7d4

#endif

#ifdef DECLARE_CSR
DECLARE_CSR(muartstat, CSR_MUARTSTAT)
DECLARE_CSR(muartrx, CSR_MUARTRX)
DECLARE_CSR(muarttx, CSR_MUARTTX)
DECLARE_CSR(mbfsstat, CSR_MBFSSTAT)
DECLARE_CSR(mbfsroot, CSR_MBFSROOT)
DECLARE_CSR(mbfstarg, CSR_MBFSTARG)
DECLARE_CSR(mbfsqbase, CSR_MBFSQBASE)
DECLARE_CSR(mbfsqsize, CSR_MBFSQSIZE)
#endif
